### ISSUE TITLE
Menu at the bottom of the page disappears on CORI page when I flush page and else cache?

### ISSUE THREAD

**Issue by CaroRob** [MassLegalHelp/MassLegalHelp#17]
@kpolymorphic 

I deleted an article from a basic page MassLegalHelp.org/cori this morning.
Flushed the cache and the menu at the bottom of the page vanished.

I could/cannot figure out what is going on.
I found a child basic page and ticked 

> **Menu translation**
>  Menu link enabled only for the English language

went back to parent page ->, menu appeared, 
flushed cache -> menu vanished

Went to next child page,
Did the same - checked box so that with menu link would be enabled only for English

On parent page menu appears.
Have not flushed cache, but checked not logged in site - menu does appear.
Afraid to flush cache.

Practically all the child pages (in English) should have "menu link enabled only for English" but this did not happen at migration so we have been paying attention to those pages as we work on them.

We have also changed the content type so that this box is ticked by default when we create a new page.

For now I am afraid to flush the cache in case the menu disappears again - which makes no sense.

I have a phone call at 11:30 today but can talk/meet before or after. (Try my cell - 603 229 7163 taking dog out for walk in the woods at some point also)

Thanks - kind of urgent.

**Comment by kpolymorphic** [comment]
Trying you now, we have been slammed all day.

**Comment by kpolymorphic** [comment]
I have noticed that the menu seems to disappear at the same time the feedback form appears

**Comment by CaroRob** [comment]
Feedback form is supposed to almost(?) always be there.

Will look again - not expecting you to do more this weekend.

@purplesky2016  maybe we can look at this together on Monday - remotely. 
Working in Boston Tues and Wed so thinking to work at home on M.

**Comment by purplesky2016** [comment]
Hi Kelly,

FYI, Caroline and I tried on the dev site today what she did on the live
site, and we were able to reproduce the issues.

1. The menu on the page bottom would disappear after we remove an article
link that's "embedded" in a basic page via a dropdown, then flush the
cache.

2. Sometimes when the menu disappears the feedback webform would appear.
This is what you have seen.

However, on my local site the same actions would not replicate these
issues, they work as expected. I know I haven't run the security updates
since Feb. 2018, but that should not have impact on these issues, for those
updates have nothing to do with webform or menu.

At the moment, I am going to investigate how the feedback form is
displayed, i.e. to fully understand the conditions for displaying it. We
saw some visibility rules in panelizer for it, but they only partially
explain how this form actual displays.

(Two weeks ago we deleted a few unused webforms and that caused the menu on
the left pane to malfunction, just another weird connection between webform
and menu on our site.)

Lily

**Comment by purplesky2016** [comment]
Oh, we restored the database on dev, so in case you want to work there, you
won't see those issues that we created earlier.

**Comment by CaroRob** [comment]
Yes.
@purplesky2016 is in on Monday 10/29- would that work?

She is also in on  Wednesday Halloween, but we can only meet before 12:30 that day.

**Comment by kpolymorphic** [comment]
Monday is great for me! What about 11 am?

**Comment by CaroRob** [comment]
Yes we can do it!
Thanks see you then.
